
// console.log("js live Ramono-project")

const token = "10166261980010720";
let $div = $("div");
const $ul = $(".search-results")
const $ulInfo = $("#info")
const sResults = []
let updatedUserSearch = "";
const $input = $("input")
const $button = $("button")
let $span = $("span")


// put a click event on the button
$button.on("click", () => {
    $("#image").empty();// cleans image for every click
    $("#info").empty(); // cleans info

    // get the text the user types
    const searchTerm = $input.val()
    // make the api call

    // $div.prepend(`Click on the desired Search Results to see info:`); not
    $.ajax({
        url: `https://www.superheroapi.com/api.php/${token}/search/${searchTerm}`,
    }).then((data) => {
        if (data.response == "error") {
            $span.append(data.error)

        } else {



            // to see the data we get back
            for (i in data.results) { // gets name from API and ID
                let name = "";
                const newResult = [data.results[i].name, data.results[i].id];


                let nameChar = newResult[0]
                let idChar = newResult[1]


                const $li = $("<li>")  // ul li to show search results
                $li.text(nameChar)
                $ul.append($li)

                $li.on("click", (event) => {  // event to select from search results
                    $("#image").empty();
                    $("#info").empty();
                    console.log(event.target)
                    const newSearchItem = $(event.target)
                    console.log(newSearchItem.text() + " first console log")
                    console.log(idChar) // logging the ID of the char
                    for (i in data.results) {  // to get info from first API call, goes through object looking for the correct ID
                        if (data.results[i].id === idChar) { // when ID matches
                            console.log(data.results[i].powerstats.durability) // to see if I'm getting the info from the correct character
                            const $img = $("<img id= image>");
                            $img.attr("alt", data.results[i].name) // adds alt attribute to image
                            $img.attr("src", data.results[i].image.url);// retrieves image to be displayed
                            console.log(data.results[i].image.url)
                            $img.appendTo("#image")

                            const $bio = $("#info-character")
                            const $h2 = $("<h2 class= infx>")
                            const $h3 = $("<h3 class= infx>")
                            $h3.text("click on the image to open on a different window")
                            $h2.text(`${data.results[i].name} Info: `) // h2 to announce the info of the character
                            $h2.appendTo("#image")
                            $h3.appendTo("#image")
                            $img.on("click", (event) => {
                                let url = $img.attr('src')


                                window.open(url)

                            })
                            for (const key in data.results[i].biography) { // to iterate through elements of the object in the API to get the BIO

                                const $li2 = $("<li>")
                                $li2.text(`${key.toUpperCase()} : ${data.results[i].biography[key]}`)
                                $ulInfo.append($li2)
                                console.log($li2.text())
                            }
                            for (const key in data.results[i].appearance) {// to iterate through elements of the object in the API to get the APPEARANCE info

                                const $li3 = $("<li>")
                                $li3.text(`${key.toUpperCase()} : ${data.results[i].appearance[key]}`)
                                $ulInfo.append($li3)
                                console.log($li3.text())
                            }
                            for (const key in data.results[i].work) {// to iterate through elements of the object in the API to get the WORK info

                                const $li4 = $("<li>")
                                $li4.text(`${key.toUpperCase()} : ${data.results[i].work[key]}`)
                                $ulInfo.append($li4)
                            }
                            for (const key in data.results[i].connections) {// to iterate through elements of the object in the API to get the CONNECTIONS info

                                const $li5 = $("<li>")
                                $li5.text(`${key.toUpperCase()} : ${data.results[i].connections[key]}`)
                                $ulInfo.append($li5)
                                console.log($li5.text())
                            }
                        }
                    }
                })
            }
        }
    })
    $input.val("");  // cleans the input box
    $span.text("");  // cleans other unwanted text when clicking on button
    $(".search-results").empty(); // cleans search results

})
// the next array contains all the names of the characters from the API, has been used for the autocomplete feature on the site.
$(document).ready(function () {
    var availableTags = ["A-Bomb", "Abe Sapien", "Abin Sur", "Abomination", "Abraxas", "Absorbing Man", "Adam Monroe", "Adam Strange", "Agent 13", "Agent Bob", "Agent Zero", "Air-Walker", "Ajax", "Alan Scott", "Alex Mercer", "Alex Woolsly", "Alfred Pennyworth", "Alien", "Allan Quatermain", "Amazo", "Ammo", "Ando Masahashi", "Angel", "Angel", "Angel Dust", "Angel Salvadore", "Angela", "Animal Man", "Annihilus", "Ant-Man", "Ant-Man II", "Anti-Monitor", "Anti-Spawn", "Anti-Venom", "Apocalypse", "Aquababy", "Aqualad", "Aquaman", "Arachne", "Archangel", "Arclight", "Ardina", "Ares", "Ariel", "Armor", "Arsenal", "Astro Boy", "Atlas", "Atlas", "Atom", "Atom", "Atom Girl", "Atom II", "Atom III", "Atom IV", "Aurora",

        "Azazel",
        "Azrael",
        "Aztar",
        "Bane",
        "Banshee",
        "Bantam",
        "Batgirl",
        "Batgirl",
        "Batgirl III",
        "Batgirl IV",
        "Batgirl V",
        "Batgirl VI",
        "Batman",
        "Batman",
        "Batman II",
        "Battlestar",
        "Batwoman V",
        "Beak",
        "Beast",
        "Beast Boy",
        "Beetle",
        "Ben 10",
        "Beta Ray Bill",
        "Beyonder",
        "Big Barda",
        "Big Daddy",
        "Big Man",
        "Bill Harken",
        "Billy Kincaid",
        "Binary",
        "Bionic Woman",
        "Bird-Brain",
        "Bird-Man",
        "Bird-Man II",
        "Birdman",
        "Bishop",
        "Bizarro",
        "Black Abbott",
        "Black Adam",
        "Black Bolt",
        "Black Canary",
        "Black Canary",
        "Black Cat",
        "Black Flash",
        "Black Goliath",
        "Black Knight III",
        "Black Lightning",
        "Black Mamba",
        "Black Manta",
        "Black Panther",
        "Black Widow",
        "Black Widow II",
        "Blackout",
        "Blackwing",
        "Blackwulf",
        "Blade",
        "Blaquesmith",
        "Bling!",
        "Blink",
        "Blizzard",
        "Blizzard",
        "Blizzard II",
        "Blob",
        "Bloodaxe",
        "Bloodhawk",
        "Bloodwraith",
        "Blue Beetle",
        "Blue Beetle",
        "Blue Beetle II",
        "Blue Beetle III",
        "Boba Fett",
        "Bolt",
        "Bomb Queen",
        "Boom-Boom",
        "Boomer",
        "Booster Gold",
        "Box",
        "Box III",
        "Box IV",
        "Brainiac",
        "Brainiac 5",
        "Brother Voodoo",
        "Brundlefly",
        "Buffy",
        "Bullseye",
        "Bumblebee",
        "Bumbleboy",
        "Bushido",
        "Cable",
        "Callisto",
        "Cameron Hicks",
        "Cannonball",
        "Captain America",
        "Captain Atom",
        "Captain Britain",
        "Captain Cold",
        "Captain Epic",
        "Captain Hindsight",
        "Captain Mar-vell",
        "Captain Marvel",
        "Captain Marvel",
        "Captain Marvel II",
        "Captain Midnight",
        "Captain Planet",
        "Captain Universe",
        "Carnage",
        "Cat",
        "Cat II",
        "Catwoman",
        "Cecilia Reyes",
        "Century",
        "Cerebra",
        "Chamber",
        "Chameleon",
        "Changeling",
        "Cheetah",
        "Cheetah II",
        "Cheetah III",
        "Chromos",
        "Chuck Norris",
        "Citizen Steel",
        "Claire Bennet",
        "Clea",
        "Cloak",
        "Clock King",
        "Cogliostro",
        "Colin Wagner",
        "Colossal Boy",
        "Colossus",
        "Copycat",
        "Corsair",
        "Cottonmouth",
        "Crimson Crusader",
        "Crimson Dynamo",
        "Crystal",
        "Curse",
        "Cy-Gor",
        "Cyborg",
        "Cyborg Superman",
        "Cyclops",
        "Cypher",
        "Dagger",
        "Danny Cooper",
        "Daphne Powell",
        "Daredevil",
        "Darkhawk",
        "Darkman",
        "Darkseid",
        "Darkside",
        "Darkstar",
        "Darth Maul",
        "Darth Vader",
        "Dash",
        "Data",
        "Dazzler",
        "Deadman",
        "Deadpool",
        "Deadshot",
        "Deathlok",
        "Deathstroke",
        "Demogoblin",
        "Destroyer",
        "Diamondback",
        "DL Hawkins",
        "Doc Samson",
        "Doctor Doom",
        "Doctor Doom II",
        "Doctor Fate",
        "Doctor Octopus",
        "Doctor Strange",
        "Domino",
        "Donatello",
        "Donna Troy",
        "Doomsday",
        "Doppelganger",
        "Dormammu",
        "Dr Manhattan",
        "Drax the Destroyer",
        "Ego",
        "Elastigirl",
        "Electro",
        "Elektra",
        "Elle Bishop",
        "Elongated Man",
        "Emma Frost",
        "Enchantress",
        "Energy",
        "ERG-1",
        "Chracter Name",
        "Ethan Hunt",
        "Etrigan",
        "Evil Deadpool",
        "Evilhawk",
        "Exodus",
        "Fabian Cortez",
        "Falcon",
        "Fallen One II",
        "Faora",
        "Feral",
        "Fighting Spirit",
        "Fin Fang Foom",
        "Firebird",
        "Firelord",
        "Firestar",
        "Firestorm",
        "Firestorm",
        "Fixer",
        "Flash",
        "Flash Gordon",
        "Flash II",
        "Flash III",
        "Flash IV",
        "Forge",
        "Franklin Richards",
        "Franklin Storm",
        "Frenzy",
        "Frigga",
        "Galactus",
        "Gambit",
        "Gamora",
        "Garbage Man",
        "Gary Bell",
        "General Zod",
        "Genesis",
        "Ghost Rider",
        "Ghost Rider II",
        "Giant-Man",
        "Giant-Man II",
        "Giganta",
        "Gladiator",
        "Goblin Queen",
        "Godzilla",
        "Gog",
        "Goku",
        "Goliath",
        "Goliath",
        "Goliath",
        "Goliath IV",
        "Gorilla Grodd",
        "Granny Goodness",
        "Gravity",
        "Greedo",
        "Green Arrow",
        "Green Goblin",
        "Green Goblin II",
        "Green Goblin III",
        "Green Goblin IV",
        "Groot",
        "Guardian",
        "Guy Gardner",
        "Hal Jordan",
        "Han Solo",
        "Hancock",
        "Harley Quinn",
        "Harry Potter",
        "Havok",
        "Hawk",
        "Hawkeye",
        "Hawkeye II",
        "Hawkgirl",
        "Hawkman",
        "Hawkwoman",
        "Hawkwoman II",
        "Hawkwoman III",
        "Heat Wave",
        "Hela",
        "Hellboy",
        "Hellcat",
        "Hellstorm",
        "Hercules",
        "Hiro Nakamura",
        "Hit-Girl",
        "Hobgoblin",
        "Hollow",
        "Hope Summers",
        "Howard the Duck",
        "Hulk",
        "Human Torch",
        "Huntress",
        "Husk",
        "Hybrid",
        "Hydro-Man",
        "Hyperion",
        "Iceman",
        "Impulse",
        "Indiana Jones",
        "Indigo",
        "Ink",
        "Invisible Woman",
        "Iron Fist",
        "Iron Man",
        "Iron Monger",
        "Isis",
        "Jack Bauer",
        "Jack of Hearts",
        "Jack-Jack",
        "James Bond",
        "James T. Kirk",
        "Jar Jar Binks",
        "Jason Bourne",
        "Jean Grey",
        "Jean-Luc Picard",
        "Jennifer Kale",
        "Jesse Quick",
        "Jessica Cruz",
        "Jessica Jones",
        "Jessica Sanders",
        "Jigsaw",
        "Jim Powell",
        "JJ Powell",
        "Johann Krauss",
        "John Constantine",
        "John Stewart",
        "John Wraith",
        "Joker",
        "Jolt",
        "Jubilee",
        "Judge Dredd",
        "Juggernaut",
        "Junkpile",
        "Justice",
        "Jyn Erso",
        "K-2SO",
        "Kang",
        "Kathryn Janeway",
        "Katniss Everdeen",
        "Kevin 11",
        "Kick-Ass",
        "Kid Flash",
        "Kid Flash II",
        "Killer Croc",
        "Killer Frost",
        "Kilowog",
        "King Kong",
        "King Shark",
        "Kingpin",
        "Klaw",
        "Kool-Aid Man",
        "Kraven II",
        "Kraven the Hunter",
        "Krypto",
        "Kyle Rayner",
        "Kylo Ren",
        "Lady Bullseye",
        "Lady Deathstrike",
        "Leader",
        "Leech",
        "Legion",
        "Leonardo",
        "Lex Luthor",
        "Light Lass",
        "Lightning Lad",
        "Lightning Lord",
        "Living Brain",
        "Living Tribunal",
        "Liz Sherman",
        "Lizard",
        "Lobo",
        "Loki",
        "Longshot",
        "Luke Cage",
        "Luke Campbell",
        "Luke Skywalker",
        "Luna",
        "Lyja",
        "Mach-IV",
        "Machine Man",
        "Magneto",
        "Magog",
        "Magus",
        "Man of Miracles",
        "Man-Bat",
        "Man-Thing",
        "Man-Wolf",
        "Mandarin",
        "Mantis",
        "Martian Manhunter",
        "Marvel Girl",
        "Master Brood",
        "Master Chief",
        "Match",
        "Matt Parkman",
        "Maverick",
        "Maxima",
        "Maya Herrera",
        "Medusa",
        "Meltdown",
        "Mephisto",
        "Mera",
        "Metallo",
        "Metamorpho",
        "Meteorite",
        "Metron",
        "Micah Sanders",
        "Michelangelo",
        "Micro Lad",
        "Mimic",
        "Minna Murray",
        "Misfit",
        "Miss Martian",
        "Mister Fantastic",
        "Mister Freeze",
        "Mister Knife",
        "Mister Mxyzptlk",
        "Mister Sinister",
        "Mister Zsasz",
        "Mockingbird",
        "MODOK",
        "Mogo",
        "Mohinder Suresh",
        "Moloch",
        "Molten Man",
        "Monarch",
        "Monica Dawson",
        "Moon Knight",
        "Moonstone",
        "Morlun",
        "Morph",
        "Moses Magnum",
        "Mr Immortal",
        "Mr Incredible",
        "Ms Marvel II",
        "Multiple Man",
        "Mysterio",
        "Mystique",
        "Namor",
        "Namor",
        "Namora",
        "Namorita",
        "Naruto Uzumaki",
        "Nathan Petrelli",
        "Nebula",
        "Negasonic Teenage Warhead",
        "Chracter Name",
        "Nick Fury",
        "Nightcrawler",
        "Nightwing",
        "Niki Sanders",
        "Nina Theroux",
        "Nite Owl II",
        "Northstar",
        "Nova",
        "Nova",
        "Odin",
        "Offspring",
        "Omega Red",
        "Omniscient",
        "One Punch Man",
        "One-Above-All",
        "Onslaught",
        "Oracle",
        "Osiris",
        "Overtkill",
        "Ozymandias",
        "Parademon",
        "Paul Blart",
        "Penance",
        "Penance I",
        "Penance II",
        "Penguin",
        "Phantom",
        "Phantom Girl",
        "Phoenix",
        "Plantman",
        "Plastic Lad",
        "Plastic Man",
        "Plastique",
        "Poison Ivy",
        "Polaris",
        "Power Girl",
        "Power Man",
        "Predator",
        "Professor X",
        "Professor Zoom",
        "Psylocke",
        "Punisher",
        "Purple Man",
        "Pyro",
        "Q",
        "Quantum",
        "Question",
        "Quicksilver",
        "Quill",
        "Ra's Al Ghul",
        "Rachel Pirzad",
        "Rambo",
        "Raphael",
        "Raven",
        "Ray",
        "Razor-Fist II",
        "Red Arrow",
        "Red Hood",
        "Red Hulk",
        "Red Mist",
        "Red Robin",
        "Red Skull",
        "Red Tornado",
        "Redeemer II",
        "Redeemer III",
        "Renata Soliz",
        "Rey",
        "Rhino",
        "Rick Flag",
        "Riddler",
        "Rip Hunter",
        "Ripcord",
        "Robin",
        "Robin II",
        "Robin III",
        "Robin V",
        "Robin VI",
        "Rocket Raccoon",
        "Rogue",
        "Ronin",
        "Rorschach",
        "Sabretooth",
        "Sage",
        "Sandman",
        "Sasquatch",
        "Sauron",
        "Savage Dragon",
        "Scarecrow",
        "Scarlet Spider",
        "Scarlet Spider II",
        "Scarlet Witch",
        "Scorpia",
        "Scorpion",
        "Sebastian Shaw",
        "Sentry",
        "Shadow King",
        "Shadow Lass",
        "Shadowcat",
        "Shang-Chi",
        "Shatterstar",
        "She-Hulk",
        "She-Thing",
        "Shocker",
        "Shriek",
        "Shrinking Violet",
        "Sif",
        "Silk",
        "Silk Spectre",
        "Silk Spectre II",
        "Silver Surfer",
        "Silverclaw",
        "Simon Baz",
        "Sinestro",
        "Siren",
        "Siren II",
        "Siryn",
        "Skaar",
        "Snake-Eyes",
        "Snowbird",
        "Sobek",
        "Solomon Grundy",
        "Songbird",
        "Space Ghost",
        "Spawn",
        "Spectre",
        "Speedball",
        "Speedy",
        "Speedy",
        "Spider-Carnage",
        "Spider-Girl",
        "Spider-Gwen",
        "Spider-Man",
        "Spider-Man",
        "Spider-Man",
        "Spider-Woman",
        "Spider-Woman II",
        "Spider-Woman III",
        "Spider-Woman IV",
        "Spock",
        "Spyke",
        "Stacy X",
        "Star-Lord",
        "Stardust",
        "Starfire",
        "Stargirl",
        "Static",
        "Steel",
        "Stephanie Powell",
        "Steppenwolf",
        "Storm",
        "Stormtrooper",
        "Sunspot",
        "Superboy",
        "Superboy-Prime",
        "Supergirl",
        "Superman",
        "Swamp Thing",
        "Swarm",
        "Sylar",
        "Synch",
        "T-1000",
        "T-800",
        "T-850",
        "T-X",
        "Taskmaster",
        "Tempest",
        "Thanos",
        "The Cape",
        "The Comedian",
        "Thing",
        "Thor",
        "Thor Girl",
        "Thunderbird",
        "Thunderbird II",
        "Thunderbird III",
        "Thunderstrike",
        "Thundra",
        "Tiger Shark",
        "Tigra",
        "Tinkerer",
        "Titan",
        "Toad",
        "Toxin",
        "Toxin",
        "Tracy Strauss",
        "Trickster",
        "Trigon",
        "Triplicate Girl",
        "Triton",
        "Two-Face",
        "Ultragirl",
        "Ultron",
        "Utgard-Loki",
        "Vagabond",
        "Valerie Hart",
        "Valkyrie",
        "Vanisher",
        "Vegeta",
        "Venom",
        "Venom II",
        "Venom III",
        "Venompool",
        "Vertigo II",
        "Vibe",
        "Vindicator",
        "Vindicator",
        "Violator",
        "Violet Parr",
        "Vision",
        "Vision II",
        "Vixen",
        "Vulcan",
        "Vulture",
        "Walrus",
        "War Machine",
        "Warbird",
        "Warlock",
        "Warp",
        "Warpath",
        "Wasp",
        "Watcher",
        "Weapon XI",
        "White Canary",
        "White Queen",
        "Wildfire",
        "Winter Soldier",
        "Wiz Kid",
        "Wolfsbane",
        "Wolverine",
        "Wonder Girl",
        "Wonder Man",
        "Wonder Woman",
        "Wondra",
        "Wyatt Wingfoot",
        "X-23",
        "X-Man",
        "Yellow Claw",
        "Yellowjacket",
        "Yellowjacket II",
        "Ymir",
        "Yoda",
        "Zatanna",
        "Zoom",
    ]
    $("#tags").autocomplete({  // taken from jQuery.ui this widget executes the autocomplete feature, jquery.ui has been linked from html
        source: availableTags
    })



})

